### ISSUE TITLE
upload `2.2` to hackage

### ISSUE THREAD

**Issue by sboosali** [raaz-crypto/raaz#392]
`2.0` doesn't build with `ghc-8.6.3.`  (and i assume `2.2` has the required `Semigroup` instances).

```
[ 3 of 54] Compiling Raaz.Core.MonoidalAction ( Raaz/Core/MonoidalAction.hs, dist/build/Raaz/Core/MonoidalAction.o )

Raaz/Core/MonoidalAction.hs:100:10: error:
    • Could not deduce (Semigroup (SemiR space m))
        arising from the superclasses of an instance declaration
      from the context: Distributive m space
        bound by the instance declaration
        at Raaz/Core/MonoidalAction.hs:100:10-55
    • In the instance declaration for ‘Monoid (SemiR space m)’
    |
100 | instance Distributive m space => Monoid (SemiR space m) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by piyush-kurur** [comment]
On Sat, Feb 16, 2019 at 12:17:13AM -0800, Spiros Boosalis wrote:
> `2.0` doesn't build with `ghc-8.6.3.`  (and i assume `2.2` has the required `Semigroup` instances).
> 
> ```
> [ 3 of 54] Compiling Raaz.Core.MonoidalAction ( Raaz/Core/MonoidalAction.hs, dist/build/Raaz/Core/MonoidalAction.o )
> 
> Raaz/Core/MonoidalAction.hs:100:10: error:
>     • Could not deduce (Semigroup (SemiR space m))
>         arising from the superclasses of an instance declaration
>       from the context: Distributive m space
>         bound by the instance declaration
>         at Raaz/Core/MonoidalAction.hs:100:10-55
>     • In the instance declaration for ‘Monoid (SemiR space m)’
>     |
> 100 | instance Distributive m space => Monoid (SemiR space m) where
>     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```


Thanks for the interest in raaz. I am assuming you meant version
0.2.2. I had a quick look into the changes. Mostly it has to do with
Semigroup becoming a super class of Monoid since base 0.4.11.  I
attempted this but it is a series of cpp matches on the base version
and is a bit painful to write.  Meanwhile, raaz is undergoing a lot of
changes for version 0.3. One of the fundamental change is the use of
backpack which gives a cleaner internals to raaz and some flexibility
like plugging in custom implementations (via backpack).  See the
Changelogs in the head to get an idea of what is planned.

https://github.com/raaz-crypto/raaz/blob/master/CHANGELOG.md

So in this context, do you really want a version 0.2.2. I can try
getting one such up but it will be some CPP work particularly if you
have some code that depend on it.


Regards,

ppk

**Comment by sboosali** [comment]
`raaz` is great, but no worries! (it's not urgent).

btw, I wrote a few macros to help myself with compatibility (which you might find useful):

https://github.com/sboosali/skeletor/blob/195168a46ddd33e123fda89f140c39477992f95d/projects/default/xxx-package-xxx/include/HsSbooMacros.h#L106

**Comment by piyush-kurur** [comment]
@sboosali  Your macros are really interesting.  Meanwhile I have a pull request (#394) that seems to work for me. I had to tweak the cabal install versions in the travis builds. See if it works for you.

**Comment by piyush-kurur** [comment]
@sboosali I have uploaded the stuff to hackage (well it is version 0.2.1). And the cabal build matrix seems to suggest that things are working well https://matrix.hackage.haskell.org/#/package/raaz. 

Closing this issue

**Comment by piyush-kurur** [comment]
Just to point out the interface will break drastically in the next release 0.3.0.

**Comment by sboosali** [comment]
thanks!

it builds just fine, but I do I get this warning:

```
Starting     raaz-0.2.1 (lib)
cabal: The 'main-is' field must specify a '.hs' or '.lhs' file (even if it is
generated by a preprocessor), or it may specify a C/C++/obj-C source file.
```

under:

```
$ cabal --version 
cabal-install version 2.4.1.0

$ ghc --numeric-version
8.6.4
```

**Comment by sboosali** [comment]
[p.s. TIL hackage has hits own multi GHC builder server]

**Comment by piyush-kurur** [comment]
On Thu, Mar 28, 2019 at 11:53:47PM -0700, Spiros Boosalis wrote:
> thanks!
> 
> it builds just fine, but I do I get this warning:
> 

Okey I will add this to the upcoming version. I do not think it would
be feasible for 0.2.1 as it is already in hackage.

Regards,

ppk

**Comment by sboosali** [comment]
one could do a revision, but I agree, it's minor.

btw, I've never done a `cabal` revision on hackage myself, but my understanding is you want to add this extension field too if you do:

`x-revision:          1`
